"""One-time: extract SIKON & SUITUS logos from the example PDFs.

Strategy: list embedded raster images on page 1 of each PDF, pick the most
likely logo (largest image in the top portion of the page), save as PNG, and
also write a base64-embedded assets/logos.js for the web app.
"""
import base64
import os

import fitz  # PyMuPDF

PDFS = {
    "sikon": r"D:\Download\Documents\Invoice\Invoice SIKON PT CITRA PERDANA 18 Juni 2026.pdf",
    "suitus": r"D:\Download\Documents\Invoice\Suitus - Penawaran Bu Rani Kantor Koni 3 Juni 2026.pdf",
}
OUT_DIR = os.path.join(os.path.dirname(__file__), "assets")
os.makedirs(OUT_DIR, exist_ok=True)


def list_images(pdf_path):
    doc = fitz.open(pdf_path)
    page = doc[0]
    ph = page.rect.height
    found = []
    for img in page.get_images(full=True):
        xref = img[0]
        smask = img[1]  # soft-mask xref (0 = none)
        rects = page.get_image_rects(xref)
        rect = rects[0] if rects else None
        info = doc.extract_image(xref)
        found.append({
            "xref": xref,
            "smask": smask,
            "rect": rect,
            "top": rect.y0 if rect else None,
            "area": (rect.width * rect.height) if rect else 0,
            "w": info["width"],
            "h": info["height"],
            "ext": info["ext"],
            "bytes": info["image"],
        })
    return doc, page, ph, found


def pick_logo(found, ph):
    # Logo: appears in top ~25% of the page; choose the largest such image.
    top_imgs = [f for f in found if f["top"] is not None and f["top"] < ph * 0.30]
    candidates = top_imgs or found
    return max(candidates, key=lambda f: f["area"]) if candidates else None


def png_bytes(img, doc, page):
    """Return PNG bytes for the chosen image, applying soft-mask transparency."""
    pix = fitz.Pixmap(doc, img["xref"])
    if pix.colorspace and pix.colorspace.n == 4:  # CMYK -> RGB
        pix = fitz.Pixmap(fitz.csRGB, pix)
    if img.get("smask"):  # combine base image with its soft mask for real alpha
        if pix.alpha:  # drop the base image's own (opaque) alpha first
            pix = fitz.Pixmap(pix, 0)
        mask = fitz.Pixmap(doc, img["smask"])
        pix = fitz.Pixmap(pix, mask)
    return pix.tobytes("png")


def main():
    b64 = {}
    for name, path in PDFS.items():
        doc, page, ph, found = list_images(path)
        print(f"\n=== {name} === page height {ph:.0f}; {len(found)} images")
        for f in found:
            print(f"  xref={f['xref']} {f['w']}x{f['h']} {f['ext']} "
                  f"top={f['top']} area={f['area']:.0f}")
        chosen = pick_logo(found, ph)
        if not chosen:
            print(f"  !! no image found for {name}")
            continue
        data = png_bytes(chosen, doc, page)
        out = os.path.join(OUT_DIR, f"logo-{name}.png")
        with open(out, "wb") as fh:
            fh.write(data)
        b64[name] = base64.b64encode(data).decode("ascii")
        print(f"  -> saved {out} ({len(data)} bytes), chosen xref={chosen['xref']}")
        doc.close()

    # Write logos.js for the web app (data URIs, ready for pdfmake & <img>).
    js_path = os.path.join(OUT_DIR, "logos.js")
    with open(js_path, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by extract_logos.py — base64 PNG logos.\n")
        fh.write("window.LOGOS = {\n")
        for name, data in b64.items():
            fh.write(f'  {name}: "data:image/png;base64,{data}",\n')
        fh.write("};\n")
    print(f"\nWrote {js_path}")


if __name__ == "__main__":
    main()
